### ISSUE TITLE
No executable found for `ros2 run turtlesim turtle_teleop_key`

### ISSUE THREAD

**Issue by sim-eng-ii** [ros2-gbp/ros_tutorials-release#2]
I am currently following ros2 tutorials. After running 

```
ros2 run turtlesim turtle_teleop_key
```

I obtain,

```
No executable found
```
What can I do to solve this issue?

Thank you.

robotAstray

**Comment by sim-eng-ii** [comment]
when running `ros2 pkg executables turtlesim` I get, 

```
turtlesim draw_square
turtlesim mimic
turtlesim turtle_telepop_key
turtlesim turtlesim_node
```

**[UPDATE]** I was able to make this work, thank you

**Comment by fpapleux** [comment]
How did you solve it? I just installed turtlesim. I get the same response to executables but I get that same error trying ros2 run turtlesim turtlesim_mode. I've made it work before without a glitch so I'm not sure where to turn yet.

**Comment by sim-eng-ii** [comment]
Hello @fpapleux to make it work I followed the Beginner CLI tools tutorials again from the start
- https://docs.ros.org/en/galactic/Tutorials.html
